# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_delete_essays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.AlterField(
            model_name='response',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
    ]
