# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20160428_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='email_or_not',
            field=models.CharField(choices=[(1, b'Yes'), (2, b'No')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='response',
            name='income',
            field=models.CharField(choices=[(1, b'$25,000 or less'), (2, b'$25,001 - $50,000'), (3, b'$50,001 - $75,000'), (4, b'$75,001 - $100,000'), (5, b'Above $100,000')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='response',
            name='support_or_not',
            field=models.CharField(choices=[(1, b'Yes'), (2, b'No')], default=1, max_length=100),
        ),
    ]
