# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-01 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mcsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(max_length=200)),
                ('col2', models.CharField(max_length=200)),
                ('col3', models.CharField(max_length=200)),
            ],
        ),
    ]
