# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160426_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e1', models.TextField()),
                ('e2', models.TextField()),
                ('e3', models.TextField()),
                ('sub', models.BooleanField(default=False)),
            ],
        ),
    ]
