# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_essays'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Essays',
        ),
    ]
