# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20160428_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='response',
            name='age',
            field=models.CharField(choices=[(1, b'18-24'), (2, b'25-34'), (3, b'35-44'), (4, b'45-54'), (5, b'55-64'), (6, b'65+')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='response',
            name='education',
            field=models.CharField(choices=[(1, b'Not Graduate from High school'), (2, b'High school'), (3, b'College'), (4, b'Graduate school'), (5, b'Post Grduate')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='response',
            name='email_or_not',
            field=models.CharField(choices=[(0, b'Yes'), (1, b'No')], default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='response',
            name='income',
            field=models.CharField(choices=[(1, b'$25,000 or less'), (2, b'$25,001 - $50,000'), (3, b'$50,001 - $75,000'), (4, b'$75,001 - $100,000'), (5, b'Above $100,000')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='response',
            name='politics',
            field=models.CharField(choices=[(1, b'Very conservative'), (2, b'Moderately conservative'), (3, b'Neither'), (4, b'Moderately liberal'), (5, b'Very liberal')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='response',
            name='support_or_not',
            field=models.CharField(choices=[(0, b'Yes'), (1, b'No')], default=0, max_length=2),
        ),
    ]
