# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20160428_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='email_or_not',
            field=models.CharField(choices=[(0, b'Yes'), (1, b'No')], default=b'Yes', max_length=100),
        ),
        migrations.AlterField(
            model_name='response',
            name='support_or_not',
            field=models.CharField(choices=[(0, b'Yes'), (1, b'No')], default=b'Yes', max_length=100),
        ),
    ]
