# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20160428_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 28, 14, 14, 2, 68209, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
